#!/bin/sh

cd `dirname $0`

file_name=$1
date=`date "+%Y-%m-%dT%H:%M:%S+09:00"`

cp ./template.md ./${file_name}.md
sed -i -e "s/this_is_title/$file_name/g" ./${file_name}.md
sed -i -e "s/this_is_date/$date/g" ./${file_name}.md
mv ./${file_name}.md ../articles/
